### PR TITLE
table cell flex -> nowrap

### LINKED ISSUE #2265: Metadata table with multi-line values
If a value on the right wraps across multiple lines, the the light line that should be separating rows get broken.
Screen Shot 2021-11-30 at 5 05 22 PM

### PR DESCRIPTION
**Pull request by mccalluc**
Fix #2265
Screen Shot 2021-12-01 at 12 20 54 PM

### CODE REVIEW

**Review by john-conroy — CHANGES_REQUESTED** [review]
I think this negatively impacts the text and icon alignment. Can you add `white-space: nowrap;` to the existing styles?

**Comment by mccalluc** [comment]
@john-conroy : Sorry, I should have made it more clear what this fixes -- From the referenced issue:

Screen Shot 2021-11-30 at 5 05 22 PM

Switching to `TableCell` fixes the broken line, but the info icons get wrapped: The no-wrap fixes that. Perhaps a flex component within the `TableCell` would do what you want?

**Comment by john-conroy** [comment]
The `display: flex; align-items: center;` styles align the icon and text. See the screenshot of how it currently looks on prod. The icons in your screenshots are ever so slightly off center.

Screen Shot 2021-12-06 at 4 37 26 PM

**Comment by mccalluc** [comment]
Just closing this for now.

**Pull request closed without merging**
