### PR TITLE
Updates to support CCF EUI v3.0

### PR DESCRIPTION
**Pull request by bherr2**

### CODE REVIEW

**Comment by mccalluc** [comment]
@bherr2 -- Does this mean the new organs should be ready to go, or is that something separate? I'll check this branch out locally and make sure it works.

**Comment by bherr2** [comment]
Yes, all new organs are integrated

**Review by mccalluc — COMMENTED** [review]
The component on the organ pages hasn't changed that I can see: That's the right behavior?
I see that it no longer has the Elasticsearch index as a parameter... Does this mean that it is hard-coded to point at the production instance now? I think that's fine, but I'd like to make sure my understanding is correct.

**Comment by bherr2** [comment]
Yes, we now use the ccf-api endpoint for querying. This update was mainly for the EUI, I haven't looked closely at the organ-info other than to make sure the works. Probably do need to update organ page info.

**Comment by bherr2** [comment]
Is [this](https://github.com/hubmapconsortium/portal-ui/blob/eui-3.0/organ-utils/descriptions.yaml) what needs updated to add more organs to the organ-info page?

**Comment by bherr2** [comment]
I think that piece may need some discussion to get right.

**Comment by mccalluc** [comment]
> Is [this](https://github.com/hubmapconsortium/portal-ui/blob/eui-3.0/organ-utils/descriptions.yaml) what needs updated to add more organs to the organ-info page?

yep, but I've already made PRs for each new organ: [Liver](https://github.com/hubmapconsortium/portal-ui/pull/2335/files), for example.

I think this PR is fine to merge (we've been letting the original authors do the merge to avoid confusion), and then I'll take all those organ PRs, check that they look good, and merge... unless you want to?

**Review by mccalluc — APPROVED** [review]

**Comment by bherr2** [comment]
Ok sounds good. You can do the first pass on the new organs and let me know if there are issues. Glad to help.

**Pull request merged**
