### PR TITLE
Unpublished Assays Fixed

### LINKED ISSUE #1614: For some unpublished datasets: 'NoneType' object has no attribute 'build_vitessce_conf'
For example, on https://portal.hubmapconsortium.org/browse/dataset/03267ea965778d4745d7802293ff6ecf, once you log in, there's a 500. Error log:
```
[2021-03-09 21:58:13,807] ERROR in app: Exception on /browse/dataset/db1b2d14e55e68f4f1473675ae1f49cb [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/routes_main.py", line 98, in details
    'vitessce_conf': client.get_vitessce_conf(entity)
  File "./app/api/client.py", line 143, in get_vitessce_conf
    conf = vc.build_vitessce_conf()
AttributeError: 'NoneType' object has no attribute 'build_vitessce_conf'
```

Looking at the code:
```
            vc = get_view_config_class_for_data_types(entity=entity, nexus_token=self.nexus_token)
            conf = vc.build_vitessce_conf()
```
and farther back:
```
def get_view_config_class_for_data_types(entity, nexus_token):
    ...
    if "rna" in hints:
        return RNASeqConf(entity=entity, nexus_token=nexus_token, is_mock=False)
    if "atac" in hints:
        return ATACSeqConf(entity=entity, nexus_token=nexus_token, is_mock=False)
```
... and that's just the end: We're falling off the end without a match.

TODO:
- Return some default Conf object at the end, if everything else has failed.
- See if these datasets that cause errors should get special treatment, or is the to-be-implemented default sufficient?

### PR DESCRIPTION
**Pull request by ilan-gold**
Fixes #1614.

To try out, it looks like http://localhost:5001/browse/dataset/03267ea965778d4745d7802293ff6ecf works now.

### CODE REVIEW

**Comment by mccalluc** [comment]
Cool -- thanks!
- Is this in some sense still an error? Like should there be handling for it, but it's type we haven't seen yet?
- Would it be ok if I tweaked it to introduce a NullConf, that returns `{}`? I worry about having agreements (Like special handling for None) spread across the code.
- Would like to add this to the tests.

**Comment by ilan-gold** [comment]
@mccalluc Sure we can do those things.  This isn't an error.  This is the correct thing to do, return emtpy `json` for assays that have no configuration, so a default class is fine if it returns `{}`. The tests will look almost identical to the `test_assays` test except they will call the the function instead of instantiating the test.  We'll need to mock the type client, which I wanted to avoid doing because it seemed a little challenging based on Joel's PR.  Happy to do it though, or you can if you would like.

**Comment by mccalluc** [comment]
@ilan-gold -- from slack: I’m going to branch and tweak it just a bit: Just want to be sure I’m not stepping on your toes. Thanks for providing a bit of context.

**Comment by mccalluc** [comment]
Replaced by #1616

**Pull request closed without merging**
