### PR TITLE
Mccalluc/npm versioning

### PR DESCRIPTION
**Pull request by mccalluc**
The real test will be seeing if the script works from day to day, but let me know if you see problems.

### CODE REVIEW

**Comment by mccalluc** [comment]
@john-conroy : I can reproduce the travis error locally:
```
ERROR in ./app/static/js/components/ServiceStatusTable/ServiceStatusTable.jsx
Module not found: Error: Can't resolve 'context/package' in '/work/app/static/js/components/ServiceStatusTable'
```
I had introduced these changes in webpack.common.js:
```
  resolve: {
    extensions: [..., '.json'],
    alias: {
      ...
      context: resolve(__dirname, '../../context'),
    },
  },
```
It works on dev, but not for the prod build. Does anything strike you?

**Comment by john-conroy** [comment]
Could be an issue with how we're copying things over in docker?

**Comment by mccalluc** [comment]
@john-conroy : D'oh: Of course the `context` directory itself isn't going to work in Docker... we just copy the stuff inside it. Thanks!

**Review by john-conroy — APPROVED** [review]
Alternatively, you could use webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) to make `VERSION` available throughout. I don't have a strong preference, but it's probably better to keep what is here and not pollute global namespace?

**Comment by mccalluc** [comment]
> Alternatively, you could use webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) to make `VERSION` available throughout. I don't have a strong preference, but it's probably better to keep what is here and not pollute global namespace?

I think I'll keep the status quo, but thanks for pointing that out... I don't have the webpack tools at my fingertips like I should.

**Pull request merged**
