### PR TITLE
Mccalluc/new vis submodule

### PR DESCRIPTION
**Pull request by mccalluc**
Keeping as draft until I sort out the tests, but does this seem like a horrible idea?

- Pull code into submodule: Preparing to move it into search-api.
- Reference just the subdirectory src with a symlink.

submodule version is pinned to the hash of [this PR](https://github.com/hubmapconsortium/portal-visualization/pull/1), pending review.

### CODE REVIEW

**Comment by mccalluc** [comment]
This is blocked pending approval of https://github.com/hubmapconsortium/portal-visualization/pull/1, so I want to keep it as draft to make sure it doesn't get merged by mistake, but it can be reviewed in the current state.

**Review by ilan-gold — APPROVED** [review]

**Comment by mccalluc** [comment]
Unblocked. @john-conroy , please review when you have a chance.

**Review by john-conroy — APPROVED** [review]
I'm not a huge fan of submodules, but most of the pain is upfront which we've already dealt with.

**Comment by mccalluc** [comment]
@john-conroy : Thanks for the feedback. Down the road, one possibility is redoing this as a python package that could be pip-installed... but I didn't want to front-load that while we're still seeing if this architecture will work.

**Pull request merged**
