### PR TITLE
`TSNE` -> `t-SNE` in SPRM

### PR DESCRIPTION
**Pull request by ilan-gold**
Requested by @ngehlenborg

### CODE REVIEW

**Review by ngehlenborg — APPROVED** [review]

**Comment by ilan-gold** [comment]
@mccalluc @john-conroy whats up with chromatic?

**Comment by mccalluc** [comment]
> @mccalluc @john-conroy whats up with chromatic?

From the [log](https://github.com/hubmapconsortium/portal-ui/runs/3553878393#step:4:105)
```
 503/Service Unavailable
```

... but nothing on their [status page](http://status.chromatic.com/)?

**Comment by ilan-gold** [comment]
I guess I'll just try re-running?  If it fails again, can I merge @mccalluc?

**Comment by mccalluc** [comment]
We want to get the release out before noon, but I don't think that request should make us be sloppier than we'd usually be. I'm going to start QA. Just restarting the CI run might be sufficient... if it persists, loop in John?

**Pull request merged**
