### PR TITLE
NickAkhmetov/HMP-457 Add workspace session renewal

### PR DESCRIPTION
**Pull request by NickAkhmetov**
This PR adds an alert to the top of the workspaces list which allows for the renewal of active workspace sessions.

https://github.com/hubmapconsortium/portal-ui/assets/19957804/9f2aa718-3693-4dae-be85-13c96e833998

Ideas for additional improvements:
- Adding a threshold time at which to start displaying that alert; right now, it displays this alert whenever any workspace is active
- Linking to the running workspace's detail page as part of the alert

### CODE REVIEW

**Review by john-conroy — COMMENTED** [review]
The alignment of the text and button looks slightly off?

**Comment by NickAkhmetov** [comment]
> The alignment of the text and button

This was due to the alert applying some additional padding around the action by default; it should be resolved now.

image
image

**Review by john-conroy — APPROVED** [review]
> Adding a threshold time at which to start displaying that alert; right now, it displays this alert whenever any workspace is active

I think this is okay for now. As users will be generally unfamiliar with the workspaces feature and its limitations we should make this information immediately available. Especially since opening a workspace takes you out of the portal.

> Linking to the running workspace's detail page as part of the alert

All for it!

We might also want to think about adding a confirm dialog of some sort.

**Comment by NickAkhmetov** [comment]
> Linking to the running workspace's detail page as part of the alert

Created HMP-514 to track this 👍🏻 

> We might also want to think about adding a confirm dialog of some sort.

We have HMP-502 reported for confirming deletion, so I'm a bit more hesitant with this since renewing isn't as destructive an action; introducing another confirmation for renewing the session might cause confirmation fatigue for users, which can cause accidental deletions due to user error/autopilot.

**Pull request merged**
