### PR TITLE
Add showcase for cell type annotations

### PR DESCRIPTION
**Pull request by keller-mark**
Depends the next release of vitessce v0.1.8

### CODE REVIEW

**Comment by keller-mark** [comment]
This got messed up when I pulled in the changes from master

**Comment by ilan-gold** [comment]
I just updated my branch, trying to fix that but now you have conflicts.

**Comment by mccalluc** [comment]
@keller-mark : Can this branch be deleted, or is it still in use?

**Comment by keller-mark** [comment]
It can be deleted

**Pull request closed without merging**
