### PR TITLE
Mccalluc/query multiple genes

### LINKED ISSUE #1943: Query multiple genes API

### LINKED ISSUE #1944: Query multiple genes UI
Builds on #1943

### PR DESCRIPTION
**Pull request by mccalluc**
Towards #1943, Fix #1944. I don't actually remember whether the multiple values in `has` create the union or the intersection... @SFD5311, can you remind us which it is, and @tsliaw, can you confirm that that's what we want in the UI?

### CODE REVIEW

**Comment by SFD5311** [comment]
@mccalluc The default value for logical operator across query types is "or," so by default we're taking the union.  The API supports overriding this default, but we didn't expose that parameter to the client.  Also worth mentioning here that the logical operator parameter in this case is actually applied to the cells in the datasets and not the datasets themselves.  So if we provide multiple genes as inputs, the results will be the datasets in which min_cell_percentage of cells express one gene or the other.  If what's desired is the datasets in which min_cell_percentage of cells express gene 1 or min_cell_percentage of cells express gene 2, the set union operator would be needed for that.

**Comment by mccalluc** [comment]
@tsliaw -- can you review what Sean wrote above, and see if that's the behavior we want to offer in the UI, or not?

**Comment by tsliaw** [comment]
@mccalluc  I'm not quite sure if that's the behavior we want, so I will put this on the UI agenda for Nils to decide

**Comment by mccalluc** [comment]
Ok, I think the UI work here is good, but I'll unlink the API issue, and add a note there about our plan to get clarification.

**Pull request merged**
