### PR TITLE
Mccalluc/workspaces message

### PR DESCRIPTION
**Pull request by mccalluc**
I believe that both sides have strong ideas about what the text should be, but I can not read your minds. This will need to be revisited as it becomes more functionally complete / leaves beta.

### CODE REVIEW

**Comment by jpuerto-psc** [comment]
@pdblood - tagging for review

**Review by pdblood — APPROVED** [review]
My primary concern was that the previous text didn't match the current functionality, so as long as this text addresses that concern, I approve.

**Review by ngehlenborg — CHANGES_REQUESTED** [review]
My preferred message is (@pdblood please agree or disagree): 

> HuBMAP Workspaces are in [beta testing](https://github.com/hubmapconsortium/portal-ui/issues/2799) and are provided as Jupyter Notebooks that may be instantiated with code blocks to perform basic and advanced operations on user-selected HuBMAP data. Instantiated workspaces can be launched on data sets, collections, and visualizations. Blank workspaces can be launched directly from this page.

**Comment by pdblood** [comment]
@ngehlenborg your message looks good as long as "workspaces can be launched on data sets, collections, and visualizations". I thought that was not yet the case. If not, then please update that sentence so it describes the current state of workspaces. As additional functionality is added, the message can be updated to reflect that.

**Review by ngehlenborg — APPROVED** [review]

**Pull request merged**
