### PR TITLE
kevin-yoo/hmp-20-trim-publication-title

### PR DESCRIPTION
**Pull request by kevinyooky**

### CODE REVIEW

**Comment by NickAkhmetov** [comment]
To clarify the feedback above: rather than trimming the text programatically, applying these styles to the `Typography` component that wraps it should 
```
    max-width: 100ch;
    overflow: hidden;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 1;
```
Useful context: 
- Good breakdown of how this works in css-tricks: https://css-tricks.com/almanac/properties/l/line-clamp/
- MDN docs for a more formal definition: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp

**Comment by kevinyooky** [comment]
Hey thanks for providing me the css code, really appreciate it. I applied it, but it is not working, there are potential confounding variable as to why this is the case, my guess is that MUI Typography has its own styling that is interfering with it or it could be something else. 

For the sake of simplicity, I will go with a javascript one-liner.

**Comment by NickAkhmetov** [comment]
I opened up #3138 with a demo of the CSS solution - the `100ch` max-width was too large in my original suggestion.

**Comment by kevinyooky** [comment]
As discussed in our call, I will go ahead with this approach, ready to be merged!

**Review by NickAkhmetov — APPROVED** [review]
Ready for liftoff 🚀

**Pull request merged**
