### PR TITLE
Austenem/CAT-964 Update external processing labels

### PR DESCRIPTION
**Pull request by austenem**
## Summary

Displays EPIC datasets as being generated via external processing in dataset relationship diagrams. Previously, segmentation mask datasets were being shown as being generated via "Image Pyramid" processing due to their `vitessce-hints`.

## Design Documentation/Original Tickets

[CAT-964 Jira ticket](https://hms-dbmi.atlassian.net/browse/CAT-964?atlOrigin=eyJpIjoiMGUzNzE0MjNhOGUwNDIwMGEyY2E4MmY0ZGU4MGQ2ZDIiLCJwIjoiaiJ9)

## Testing

Verified using a segmentation mask EPIC on dev: https://portal.dev.hubmapconsortium.org/browse/dataset/22901da5f080b219a514e38381acbb0e

## Screenshots/Video

Dev:
Screenshot 2024-10-24 at 11 58 21 AM

Local:
Screenshot 2024-10-25 at 10 08 40 AM

## Checklist

- [X] Code follows the project's coding standards
    - [X] Lint checks pass locally
    - [X] New `CHANGELOG-your-feature-name-here.md` is present in the root directory, describing the change(s) in full sentences.
- [X] Unit tests covering the new feature have been added
- [X] All existing tests pass
- [X] Any relevant documentation in JIRA/Confluence has been updated to reflect the new feature
- [X] Any new functionalities have appropriate analytics functionalities added

### CODE REVIEW

**Comment by lchoy** [comment]
@austenem Would it be possible to use the assay_display_name instead of "External Process"? Acknowledging that is not what's specified in the ticket, displaying the analysis performed would be more consistent with what's shown for other dataset types.

**Comment by austenem** [comment]
> @austenem Would it be possible to use the assay_display_name instead of "External Process"? Acknowledging that is not what's specified in the ticket, displaying the analysis performed would be more consistent with what's shown for other dataset types.

That makes sense and seems like a useful addition. There isn't an `assay_display_name` present in the soft assay response, but there are `dataset-type` and `description` fields that both contain the relevant label for this EPIC. I chose to use the `dataset-type` because it appears unique to the EPIC processing type.

**Comment by john-conroy** [comment]
The `description` is the same as `assay_display_name`.

**Comment by john-conroy** [comment]
https://github.com/hubmapconsortium/search-api/blob/1e7c8af08b28c587b1bded66503c8e82b70e079e/src/hubmap_translation/addl_index_transformations/portal/add_assay_details.py#L143

**Review by NickAkhmetov — APPROVED** [review]
:shipit:

**Pull request merged**
