### PR TITLE
Start to handle image_pyramid

### PR DESCRIPTION
**Pull request by mccalluc**
Towards #982... Not sure what the behavior should be if it fails? @ilan-gold : Should we be concerned about this?

### CODE REVIEW

**Comment by ilan-gold** [comment]
This make sense but I use the `image_pyramid` type a  bunch.  An entire configuration is based on it.  I think the solution is to just use the list as is, as a data structure.

**Comment by mccalluc** [comment]
@ilan-gold : I'm concerned about relying on a particular ordering in the `data_types` list... It's been stable, but I think it's the sort of thing that they could change without realizing there's a downstream dependency.

Would you like me to continue this work, trying to take into account your concerns? Or would you like to handle it?

**Comment by ilan-gold** [comment]
@mccalluc It's up to you.  I'm not too worried, but I agree things could change without us knowing so changing this should be a priority.  I can look at this first-thing after all this Viv stuff is wrapped up - should be tomorrow or Wednesday.

**Comment by ilan-gold** [comment]
I think you can handle this if done carefully, and I can try to support you going through it if you want to take it on.

**Pull request closed without merging**
