### PR TITLE
Azimuth Fix ("Array not found ...": new scRNA-seq (10x Genomics) [Salmon])

### LINKED ISSUE #2298: Array not found at path obs/predicted.ASCT.celltype
This is observed on PROD for the new scRNA-seq (10x Genomics) [Salmon] dataset https://portal.hubmapconsortium.org/browse/dataset/7cc96210e80d5736ca38711503e4ff06 .  This is the first to be processed from a new assay type, scRNA-seq (10x Genomics v2) .

### PR DESCRIPTION
**Pull request by ilan-gold**
Fixes #2298

### CODE REVIEW

**Comment by ilan-gold** [comment]
@mccalluc This is a hack IMO so I am going to remove the test

**Comment by ilan-gold** [comment]
I suppose we could mock things....

**Comment by mccalluc** [comment]
In the meeting notes I see this:
> Identify a way to indicate the annotation is available in the portal and metadata that is queryable.

That agrees with my memory -- I read that as saying that we should wait until it's available in the metadata, and we should not try to hack around that.

Was there a separate request to get a short-term fix in place until the metadata is ready?

**Comment by ilan-gold** [comment]
We decided on using `zarr` directly....the issue playing out in `hive-developers` is preventing us from merging this because calling `zarr.open` takes forever and stalls the webpage.

**Comment by mccalluc** [comment]
Update from Ilan:
> The issue was that the roundtrip for SSL was taking too long: https://hubmapconsortium.slack.com/archives/C011RF3NQ23/p1639774415439600

**Comment by mccalluc** [comment]
Propose moving this lookup to index time. See https://github.com/hubmapconsortium/portal-visualization/pull/1.

**Comment by mccalluc** [comment]
> Propose moving this lookup to index time. See [hubmapconsortium/portal-visualization#1](https://github.com/hubmapconsortium/portal-visualization/pull/1).

That proposal was rejected at February 4 HIVE meeting. Phil Blood has responsibility for unblocking this.

**Comment by mccalluc** [comment]
Replaced by #2433 and https://github.com/hubmapconsortium/portal-visualization/pull/10

**Pull request closed without merging**
