### PR TITLE
John conroy/fix search page safari bugs

### LINKED ISSUE #1091: Clicking on a header menu breaks table on search pages in Safari
To reproduce:

1. Go to 
2. Click on "Documentation" menu.
3. Search results table now extends past the width of the page.

Before clicking the menu:

image

After clicking the menu:

image

### LINKED ISSUE #1144: Safari search table width bad (if wide -> narrow -> wide)
v0.1.5, Safari

Load the search page with a wide window; then narrow it; then re-widen it.

The table width is now several times the screen width, and the first column (the ID) is the only thing visible in the window.

Screen Shot 2020-08-31 at 12 08 37 PM

### PR DESCRIPTION
**Pull request by john-conroy**
Fix #1091. Fix #1144.

Could you also take a look at the search page in safari to confirm the bugs are fixed?

### CODE REVIEW

**Review by mccalluc — CHANGES_REQUESTED** [review]
Since it's no longer an `<a>` we don't get the cursor styling for free: Can you add the CSS for that?

Chrome works great. Thanks!

**Comment by mccalluc** [comment]
(Sorry... confused Chrome and Safari... let me check that now...)

**Comment by john-conroy** [comment]
Approved to merge after fixing the cursor?

**Comment by mccalluc** [comment]
... and Safari looks great too, apart from the cursor.

**Comment by mccalluc** [comment]
yep, please merge when the cursor is fixed. Thanks!

**Comment by john-conroy** [comment]
Worth noting, it won't show the url preview in the browser's status bar when hovering over the row link.

**Pull request merged**
