### PR TITLE
Update paths in README

### PR DESCRIPTION
**Pull request by keller-mark**
While trying to set up the development environment just now I noticed that some of the paths in the readme were out of date / incomplete.

### CODE REVIEW

**Comment by john-conroy** [comment]
Does anyone else see the travis checks stuck as pending? If so, could this be a result of the new repo protections?

**Comment by mccalluc** [comment]
> Does anyone else see the travis checks stuck as pending? If so, could this be a result of the new repo protections?

Huh: I see that too, Though the Github wrapper ones (`Travis CI - Branch`, `Travis CI - Pull Request`) are green, so we can tell that the tests are passing.

[This](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154) might be the problem, and the fix... Let me try changing those settings.

**Comment by mccalluc** [comment]
... and added that setting. We'll see if anything changes going forward.

**Comment by mccalluc** [comment]
@keller-mark : Merge?

**Comment by keller-mark** [comment]
On my end, I cannot merge, GitHub says
> Merging is blocked.
> The base branch restricts merging to authorized users. Learn more about protected branches.
> You’re not authorized to merge this pull request.

**Comment by mccalluc** [comment]
Sorry about that, just added you as admin...

**Comment by keller-mark** [comment]
Thanks, just merged

**Pull request merged**
