### PR TITLE
John conroy/fusion slide CAT-12

### PR DESCRIPTION
**Pull request by john-conroy**
- Add fusion slide to homepage carousel and enable carousel autoplay until a user navigates the slides.
- Change webp script permissions to make it executable.

The dimensions are correct, but since the image's border matches the background somewhat it seems smaller than the other images.

Screenshot 2024-01-19 at 3 13 29 PM

@tsliaw the only thing I'm unclear about is the usage of '-omics', does that seem right?

### CODE REVIEW

**Comment by john-conroy** [comment]
@tsliaw here's a screen recording which demonstrates the autoplay interval. Note that I refresh the page a second or so in.

https://github.com/hubmapconsortium/portal-ui/assets/62477388/d581f47e-6820-449f-92fe-8abab465e66d

**Comment by tsliaw** [comment]
@john-conroy I'm not sure about the "-omics" part either, I always thought the dash in front of the word isn't necessary if talking about omics. Can you share the screenshot in Slack and ask Nils?

**Review by tsliaw — DISMISSED** [review]
Carousel looks good. We might want to look at smoother transitions for the carousel going through the slides in the future though. Will include that in the homepage revisions designs for March Demo Day.

**Comment by john-conroy** [comment]
Removed the dash before 'omics' as suggested by Nils.

Screenshot 2024-01-19 at 3 41 40 PM

**Review by lchoy — APPROVED** [review]

**Pull request merged**
