### PR TITLE
Mccalluc/marked redo

### LINKED ISSUE #900: Sub headers in markdown should get anchor links
Particularly for Jonathan's donor data, having links within the page is important. Perhaps a different markdown library would offer this by default?

### LINKED ISSUE #901: Wide tables in markdown should scroll rather than spill over
At the bottom of the donor metadata page there is a particularly wide table that they would like to scroll within the page, rather than spill over.

### LINKED ISSUE #937: update styles for documentation and preview Markdown
Update that CSS to match our style guide more closely. In particular the bold headers should be replaced to better match the styles on the other pages. I also believe that the font size for the main text might be a bit too small.

### PR DESCRIPTION
**Pull request by mccalluc**
Replaces #917. Towards #1046.

Fix #901, fix #900, fix #937.

### CODE REVIEW

**Comment by mccalluc** [comment]
@ilan-gold : Huh: http://localhost:5001/docs works for me... Restart the dev server to make sure the npm dependencies are installed? (Though preview shouldn't have worked if they weren't...) Or do you not have the docs submodule pulled down? (Though `docs.md` itself is not from the submodule, so that doesn't seem like the problem.) Does `/VERSION` work?

So... not really sure, but I'd like to know that it works for you before merging.

**Comment by mccalluc** [comment]
@tsliaw : pushed a change to use `subtitle1`. (Off hand, I'm really not sure if it's supposed to be a subtitle, or something else.) Does this look right?
Screen Shot 2020-08-18 at 12 17 16 PM

**Comment by tsliaw** [comment]
Using subtitle is correct and the styling is correct now, but can you make it the theme purple color?

**Comment by ilan-gold** [comment]
@mccalluc I can see VERSION but I think you misread my comment - I was saying all of the links within that page are not working, like http://localhost:5001/docs/about.  Does this work for you?   Everything seems to be installed OK

**Comment by ilan-gold** [comment]
Which submodule is supposed to contain the docs @mccalluc?  All I see is `ingest-validation-tools` in my repo (and on Github) in terms of submodules.

**Comment by ilan-gold** [comment]
Ah I see it @mccalluc my apologies.  It was not being pulled down.

**Comment by mccalluc** [comment]
- @tsliaw : Green checkmark if the purple is good, and there's nothing else that needs to be fixed?
- @ilan-gold : If you have any process-level suggestions that would make it less confusing, that'd be great... but sometimes things are irreducibly confusing. :(

Thanks!

**Comment by ilan-gold** [comment]
@mccalluc Is it possible to somehow automate the update of sub-modules?  Or did I do something wrong?  Could we add something to `dev-start.sh` to automatically update?

**Comment by mccalluc** [comment]
We could add something to dev start, but did you see this section in the README?:
> Git does not update submodules on pull by default... but you can make it the default:
> ```
> git config --global submodule.recurse true # Run this once...
> git pull                                   # Now pulls submodules!
> ```
Would that do what you want?

**Pull request merged**
