### PR TITLE
Update Atlas Menu

### PR DESCRIPTION
**Pull request by bherr2**
- Added three more HRA previews
- Updated the CCF Portal to the HRA Portal and it's new home, humanatlas.io

### CODE REVIEW

**Review by john-conroy — APPROVED** [review]
Is `Added three more HRA previews` related to the previous PR?

**Comment by bherr2** [comment]
Nope, just adding links to the Atlas menu

**Comment by bherr2** [comment]
Added one more preview 🙂

**Comment by bherr2** [comment]
@john-conroy When will this be pushed to production?

**Comment by john-conroy** [comment]
Should be tonight. We were holding off on releases before the break out of precaution with some other changes.

**Pull request merged**
