### PR TITLE
(chore): upgrade vitessce to 1.2.2

### PR DESCRIPTION
**Pull request by ilan-gold**
This upgrade features both a speedup to the heatmap (testable on big CODEX datasets) and the upgrade of AnnData `io` capabilities to 0.8.0 of the AnnData package..

### CODE REVIEW

**Comment by mccalluc** [comment]
I'm going to try re-running failing node tests:
```
npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
```

@ilan-gold : Is there a good dataset where we can confirm the speedup? And are we expecting any changes from the AnnData upgrade? And should we poke around on localhost, or have you already done manual QA?

**Review by mccalluc — COMMENTED** [review]
there's not much code to review here... How would you like us to QA this?

**Comment by ilan-gold** [comment]
@mccalluc I did fairly extensive testing, looking at a number of datasets, and trying out various things.   The speedup should be visible on all "CODEX [Cytokit + SPRM]" datasets, especially when changing clusterings.  There shouldn't be any changes re: AnnData - mostly just noting that since in the future, we'll be able to handle AnnData 0.8.0 stores.

**Comment by ilan-gold** [comment]
So anything on this list should be faster, especailly when changing the cell sets: http://localhost:5001/search?mapped_data_types[0]=CODEX%20[Cytokit%20%2B%20SPRM]&entity_type[0]=Dataset

**Comment by ilan-gold** [comment]
If you want to test out, that'd be great, but not a requirement.

**Comment by mccalluc** [comment]
Hmm... I've updated npm, but I'm getting a python error...
```
[2022-10-03 10:31:34,143] ERROR in client: Building vitessce conf threw error: Traceback (most recent call last):
  File "/Users/chuck/github/hubmap/portal-ui/context/app/api/client.py", line 186, in get_vitessce_conf_cells_and_lifted_uuid
    vitessce_conf = builder.get_conf_cells(marker_gene=marker)
TypeError: get_conf_cells() got an unexpected keyword argument 'marker_gene'
```
Just did a `pip install -r requirments.txt` and no change, and I have no local changes in this checkout.

My guess is that something about my local environment is corrupted.

If John can confirm the speed-up in his local environment, don't let me block, but I'll try to sort things out and get back to this.

**Comment by mccalluc** [comment]
(`marker_gene` changed to `marker` in [PR 2920](https://github.com/hubmapconsortium/portal-ui/pull/2920/files)... I'm going to try merging main into this branch, which should get rid of the reference to `marker_gene`... If that works, I'll make a PR into this PR...)

**Review by mccalluc — APPROVED** [review]
Works for me now. Sorry for the slow process.

**Comment by ilan-gold** [comment]
No worries, appreciate you being thorough :)

**Pull request merged**
