### PR TITLE
Fix SPRM Stitched

### PR DESCRIPTION
**Pull request by ilan-gold**
The offsets are wrong in the generated data but something should show now regardless

`06589a380ca45237eddd0d9ea7ad2c9f` on TEST if you'd like to test should work now whereas before it would have no visualization

### CODE REVIEW

**Review by mccalluc — COMMENTED** [review]
Code looks good... but when I try it on FF on localhost:
```
8691082915633190000 exceeds MAX_SAFE_INTEGER. Precision may be lost. Please report if you get this message to https://github.com/geotiffjs/geotiff.js/issues
```
and the spinners never go away. (I've waited a couple minutes.) In the console:
```
cleared cell-sets; waiting on 2: ["cells","raster"]
cleared cell-sets; waiting on 1: ["cells"] 
cleared cells; waiting on 1: ["raster"] 
cleared cells; waiting on 0: [] 
cleared expression-matrix; waiting on 1: ["raster"] 
cleared expression-matrix; waiting on 0: []
```
From that, I would think all the data has loaded?

Having a visualization that doesn't work is one step ahead of not having a visualization. I think it might be ok to file an issue for the remaining work, and merge this... but it would be a little safer to get a working example before merging. Your call.

**Comment by ilan-gold** [comment]
@mccalluc Yes the backing data is wrong.

This is the tradeoff of doing things this way and the reason I previously had not - they are almost surely going to break the first few (or more) times around.  I don't mind merging this since it's not our fault that the data is broken.  There's no new work for us here.

**Review by mccalluc — APPROVED** [review]
> I don't mind merging this since it's not our fault that the data is broken. There's no new work for us here.

Cool -- As long as you're pretty sure it's a data problem, merging now seems good. (Would it be worth trying to catch anything in a validation phase before visualization?) Thanks!

**Comment by ilan-gold** [comment]
> > I don't mind merging this since it's not our fault that the data is broken. There's no new work for us here.
> 
> Cool -- As long as you're pretty sure it's a data problem, merging now seems good. (Would it be worth trying to catch anything in a validation phase before visualization?) Thanks!

I don't think there's much we could do here.  They ran the offsets pipeline on the wrong file so the offsets are wrong 🤷‍♂️

**Pull request merged**
